# Docker Compose v2 兼容配置
# 使用: docker compose up -d 或 docker-compose up -d

services:
  snowboy-web:
    image: rhasspy/snowboy-seasalt:latest
    container_name: snowboy-seasalt
    
    # 从源码构建（可选）
    # 取消注释下面的 build 配置并注释掉上面的 image 配置
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    
    volumes:
      # 可选：保存生成的模型到本地
      - ./models:/app/models
    
    environment:
      LANG: C.UTF-8
      # 消除警告
      PYTHONWARNINGS: "ignore::UserWarning:webrtcvad"
    
    # 健康检查（使用 Dockerfile 内置的健康检查）
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    restart: unless-stopped

